config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items

  root 'welcome#index'

  get 'show_users' => 'welcome#show_users'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :first_name, :last_name) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :first_name, :last_name) }
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.order(:dueby)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to root_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to root_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:chore, :dueby)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@items = Item.all.order(:dueby)

			@date = []
      @items.each do |item|
        @date = @date.push(item.dueby)
      end

      @date = @date.uniq
	    	
  	


  end

  def show_users
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chore %><br>
    <%= f.text_field :chore %>
  </div>
  <div class="field">
    <%= f.label :dueby %><br>
    <%= f.date_select :dueby %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', root_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Chore</th>
      <th>Dueby</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.chore %></td>
        <td><%= item.dueby %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>New item</h1>

		<%= render 'form' %>

		<%= link_to 'Back', root_path %>
		<br />
		<br />
	</div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chore:</strong>
  <%= @item.chore %>
</p>

<p>
  <strong>Dueby:</strong>
  <%= @item.dueby %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Alegreya:400,700|Roboto+Condensed|Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar-right">
    <% if user_signed_in? %>
      You are logged in as <%= current_user.email %> | 
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      You are not logged in.
      <%= link_to "Log in", user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
  </div>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1>To Do List</h1>
			<% if @date.empty? == false %>
				<% @date.each do |date| %>
					<p><%= date.strftime('%B %d, %Y') %></p>
		    	<ul>	
		    		<% @items.each do |item| %>
		      		<% if date == item.dueby %>
		      			<li>
			        		<h3><%= link_to item.chore, item, title: "Click When Done", rel: "tooltip", method: :delete, data: { confirm: 'Are you sure?' } %></h3>
			        		<p><%= link_to '', edit_item_path(item), class: "glyphicon glyphicon-pencil", title: "Click To Edit", rel: "tooltip" %></p>
			        	</li>
		    			<% end %>
		    		<% end %>
		    		<br />
		    	</ul>
		    <% end %>
		  <% end %>

		<br />

		<%= link_to 'New Item', new_item_path %>
		<br />
		<br />
	</div>
</div>

app/views/welcome/show_users.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Show Users</h1>
      <table class="table">
        <tr>
          <td>User Id</td>
          <td>First Name</td>
          <td>Last Name</td>
          <td>Email Address</td>
        </tr>	
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
    	<td><%= user.first_name %></td>
    	<td><%= user.last_name %></td>
    	<td><%= user.email %></td>
          </tr>
      <% end %>	
    </table>
  </div>
</div>